{
  config,
  lib,
  pkgs,
  ...
}:

let
  gitIdentitiesSync = pkgs.writeShellApplication {
    name = "git-identities-sync";
    runtimeInputs = [ pkgs.coreutils ];
    text = ''
      identities_dir=${lib.escapeShellArg "${config.xdg.configHome}/git/identities"}
      output_dir=${lib.escapeShellArg "${config.xdg.configHome}/git"}
      output_file="$output_dir/auto-identities.gitconfig"

      mkdir -p "$identities_dir" "$output_dir"
      temporary_file=$(mktemp "$output_file.tmp.XXXXXX")
      trap 'rm -f "$temporary_file"' EXIT

      printf '# Generated by git-identities-sync. Do not edit.\n' > "$temporary_file"

      profile_count=0
      shopt -s nullglob
      for identity_file in "$identities_dir"/*.gitconfig; do
        owner=$(basename "$identity_file" .gitconfig)
        if [[ ! "$owner" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]; then
          printf 'git-identities-sync: invalid profile name: %s\n' "$owner" >&2
          exit 1
        fi

        ${pkgs.git}/bin/git config --file "$temporary_file" --add \
          "includeIf.gitdir:~/Github/github.com/$owner/.path" "$identity_file"
        profile_count=$((profile_count + 1))
      done

      chmod 600 "$temporary_file"
      mv "$temporary_file" "$output_file"
      trap - EXIT
      printf 'Git identity conditions updated: %d profile(s)\n' "$profile_count"
    '';
  };
in
{
  home.packages = [
    pkgs.ghq
    pkgs.gh
    pkgs.lazygit
    gitIdentitiesSync
  ];
  home.sessionVariables.GIT_IDENTITIES_DIR = "${config.xdg.configHome}/git/identities";

  home.activation.syncGitIdentities = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    ${gitIdentitiesSync}/bin/git-identities-sync
  '';

  programs.git = {
    enable = true;
    settings = {
      init.defaultBranch = "main";
      core.editor = "nvim";
      ghq.root = "~/Github";
      push.autoSetupRemote = true;
      pull.rebase = false;
      merge.conflictstyle = "zdiff3";
      url."git@github.com:".insteadOf = "https://github.com/";
    };
    includes = [
      # user.name/email はマシンごとに異なるため Nix 管理から外し、
      # 各マシンで手動作成するローカルファイルから読み込む
      # (例: [user]\n  name = ...\n  email = ...)
      # デフォルトは git-user コマンドで切り替えるプロファイル
      {
        path = "~/.gitconfig.identity";
      }
      # ~/.config/git/identities/*.gitconfig のファイル名から、
      # owner ごとの includeIf を activation 時に自動生成する
      {
        path = "${config.xdg.configHome}/git/auto-identities.gitconfig";
      }
    ];
  };

  # gh CLI の一般設定（~/.config/gh/config.yml）のみ管理する。
  # 認証トークン（~/.config/gh/hosts.yml）は `hosts` オプションを使わないことで
  # Nix管理外のまま残し、`gh auth login` で個別に設定する運用を維持する。
  programs.gh = {
    enable = true;
    settings = {
      git_protocol = "https";
      aliases = {
        co = "pr checkout";
      };
    };
  };

  home.file = {
    "Library/Application Support/lazygit/config.yml" = {
      source = ./../dotfiles/lazygit/config.yml;
      force = true;
    };
    "Library/Application Support/lazygit/gen-commit-msg.sh" = {
      source = ./../dotfiles/lazygit/gen-commit-msg.sh;
      force = true;
    };
    "Library/Application Support/lazygit/prune-merged-branches.sh" = {
      source = ./../dotfiles/lazygit/prune-merged-branches.sh;
      force = true;
    };
    ".config/gh-dash/config.yml" = {
      source = ./../dotfiles/gh-dash/config.yml;
      force = true;
    };
  };
}
